// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylheyxhpacaptoecjoqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsaGV5eGhwYWNhcHRvZWNqb3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjE5MDEsImV4cCI6MjA3MTI5NzkwMX0.PxypDTNvqpLy7q_InN_JQGFX6kkZhvbhTwcVaesvQR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});